export default Language = {
   Restaurant: "Restaurants",
   searchRestaurants: "What are you looking for?",
   searchInRestaurant: "What are you looking for eating?",
   addToCart:"Add to cart",
   addToOrder:"Add to order",
   quatity:"Quantity",
   item:"Item",
   items:"Items",
   itemAddedInCart:"Item is added in cart",
   itemsAddedInCart:"Items are added in cart",
   order:"Order",
   cartSubtotal:"Cart Subtotal",
   subtotal:"Subtotal",
   proceedToCheckout:'Proceed To Checkout',
   noOrders:'There are no orders',
   noItemsInCart:'There are no items in cart',
   profile:'Profile',
   home:"Home",
   myOrders:"My Orders",
   addresses:"Addresses",
   login:"Login",
   logout:"Logout",
   forgotPassword:"Forgot Password",
   register:"Register",
   userIsNowLoggedIn:"User is now logged in",
   proceedToLoginFirst:"Login or register to continue",
   selectAddress:"Select Address",
   noAddressesAddNew:"No addresses found!",
   addAddress:"Add Address",
   enterYourAddress:"Enter your address",
   continue:"Continue",
   addressDetails:"Address Details",
   addressNumber:"Address Number",
   intercom:"Intercom",
   appartment:"Appartment number",
   entry:"Entry number",
   floor:"Floor",
   addressForDelivery:"Address for delivery",
   checkout:"Checkout",
   deliveryOrPickup:"Deliver / Pickup",
   deliveryTime:"Delivery Time",
   pickupTime:"Pickup Time",
   restaurantInformations:"Restaurant Informations",
   delivery:"Delivery",
   pickup:"Pickup",
   addNewAddress:"Add new address",
   summary:"Summary",
   deliveryMethod:"Delivery Method",
   total:"Total",
   paymentMethod:"Payment method",
   pay_with_card:"Pay with card",
   cod:"Cash on deliver",
   cop:"Cash on pickup",
   place_order:"Place order",
   orderSuccesfull:"Order has been received succefully",
   trackOrder:"You can track and see the status of the order in the orders tab.",
   ok:"Ok",
   errorOnOrder:"Error on placing the order.",
   status:"Status",
   created:"Created",
   orderDetails:"Order details",
   restaurant:"Restaurant",
   deliveryAddress:"Delivery address",
   orderTracking:"Order tracking",
   orderNumber:"Order number",
   driver:"Delivery driver",
   driverName:"Driver name",
   driverPhone:"Driver phone",
   orderOptions:"Order options",
   all:"All",
   notifications:"Notifications",
   noNotifications:"No notifications",
   restaurantClosed:"Looks like restaurant is closed at this time. Order can't be made.",
   you_can_order_items_from_different_restaurants:"You can't order items from different restaurants in single order."
  }